### ISSUE TITLE
No module named 'util.scannet200'

### ISSUE THREAD

**Issue by Evanwanna** [boschresearch/Open3DSG#2]
Hi! Thank you for your great work. When i try to create subgraphs for Scannet through running file "gen_scannet_subgraphs.py”, error "No module named 'util.scannet200'" occurred. And the file "scannet200.py" including function "nyu2scannet" cannot be found in folder "util". So I wonder if you missed this file when committing this rep or i missed something important? Looking forward to your help, thanks.

**Comment by kochsebastian** [comment]
Thank you for finding this bug. We have updated the repo to include the missing helper function.

**Comment by Evanwanna** [comment]
Ok, thanks again for your help.
