### ISSUE TITLE
Missing files

### ISSUE THREAD

**Issue by dcaceresd** [boschresearch/Open3DSG#3]
**Issue:**

I noticed that the file `train_scans.txt` is missing from the repository, after trying to execute:
```
python open3dsg/data/get_object_frame.py --mode train --dataset R3SCAN
```

**Error**
```
Traceback (most recent call last):
  File "/Open3DGS/open3dsg/data/get_object_frame.py", line 392, in <module>
    scene_data, selected_scans = read_json(root, mode)
  File "/Open3DGS/open3dsg/data/get_object_frame.py", line 116, in read_json
    selected_scans = selected_scans.union(read_txt_to_list(os.path.join(root, f'{split}_scans.txt')))
  File "/Open3DGS/open3dsg/util/util_misc.py", line 52, in read_txt_to_list
    with open(file, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/Open3DGS/datasets/3RScan/3DSSG_subset/train_scans.txt'
```
I can see that the file is not contained in [3DSSG_subset.zip](http://campar.in.tum.de/public_datasets/3DSSG/3DSSG_subset.zip) nor [here](https://drive.google.com/drive/folders/1rlzUS1d5cYo5lJCNl1G81x9HmYtn5NB5).

Also noticed that that file (along others) is aimed to be downloaded during the execution of:
```
helpers/download_3rscan_meta.sh 
```
but none of the links from tum are valid.

Can you please help me find those files?

Thank you for looking into this issue. Please let me know if you need any further information.

**Comment by kochsebastian** [comment]
The `train_scans.txt` file (among others) is supposed to be downloaded by running `download_3rscan_meta.sh`. The download links indeed seem to be broken. I will talk with the dataset authors and will keep you up-to-date´.

**Comment by kochsebastian** [comment]
Meanwhile, you can download the 3RScan metadata from here: [http://campar.in.tum.de/public_datasets/3RScan/3RScan.json](http://campar.in.tum.de/public_datasets/3RScan/3RScan.json) and the train test scans from here: [https://github.com/WaldJohannaU/3RScan/tree/master/splits](https://github.com/WaldJohannaU/3RScan/tree/master/splits) and rename the files accordingly

**Comment by kochsebastian** [comment]
download links have been updated in the repo

**Comment by vivekmadhavaram** [comment]
@kochsebastian I cant find "relationships_test.json" when running code "python open3dsg/data/get_object_frame.py --mode [train/test] --dataset [R3SCAN/SCANNET]" for R3SCAN dataset

**Comment by vivekmadhavaram** [comment]
Hi @kochsebastian,
 "/open3DSG/3RScan/3DSSG_subset/relationships_test.json" file is missing. Can you please provide it?

**Comment by kochsebastian** [comment]
3DSSG has no test split. We generated this ourselves for an ablation we did in the paper. For evaluation use the validation split.
