### ISSUE TITLE
How to use the preprocess dataset of ScanNet-ETH

### ISSUE THREAD

**Issue by mfp0610** [boschresearch/Open3DSG#4]
Hi, I wonder how to use the preprocess data you provide in your repo.
I found the only one possible match but still not the right one. https://github.com/ScanNet/ScanNet/tree/master/BenchmarkScripts/ScanNet200
Can you provide me with an exact one?

**Comment by VesVlad** [comment]
@mfp0610 Hello! Please tell me, were you able to figure out how to preprocess the data? Am I correct in understanding that we need .ply files, which can be obtained from Scannet by signing a user agreement? Or we don’t need them and we can run it somehow differently, taking into account the fact that we have scannet_2d and scannet_3d folders (the latter contains .pth files, which I also don’t quite understand where they are used)

**Comment by da13132** [comment]
> @mfp0610 Hello! Please tell me, were you able to figure out how to preprocess the data? Am I correct in understanding that we need .ply files, which can be obtained from Scannet by signing a user agreement? Or we don’t need them and we can run it somehow differently, taking into account the fact that we have scannet_2d and scannet_3d folders (the latter contains .pth files, which I also don’t quite understand where they are used)

Hello, I'm currently reproducing this project, but I've encountered a few problems. May I ask if you have successfully preprocessed the scannet_2d and scannet_3d data? The ply files should be necessary, right?

**Comment by Oliverbihop** [comment]
> > [@mfp0610](https://github.com/mfp0610) Hello! Please tell me, were you able to figure out how to preprocess the data? Am I correct in understanding that we need .ply files, which can be obtained from Scannet by signing a user agreement? Or we don’t need them and we can run it somehow differently, taking into account the fact that we have scannet_2d and scannet_3d folders (the latter contains .pth files, which I also don’t quite understand where they are used)
> 
> Hello, I'm currently reproducing this project, but I've encountered a few problems. May I ask if you have successfully preprocessed the scannet_2d and scannet_3d data? The ply files should be necessary, right?




Hello, could i ask how did you encounter this problem?
