### ISSUE TITLE
Error on Seperately Precompute 2D features

### ISSUE THREAD

**Issue by mfp0610** [boschresearch/Open3DSG#5]
Hi! Thanks a lot for your great work! 
I have met the OOM problem when running the precompute 2D feature, and when I separately ran the OpenSeg feature, I met this bug: 
`File "/data1/fanpeng/code/Open3DSG/open3dsg/models/sgpn.py", line 484, in clip_encode_pixels
    rel_clip_encoding = self.CLIP.encode_image(rel_imgs_batched).view(*rel_imgs.shape[:-3], -1)
AttributeError: 'NoneType' object has no attribute 'encode_image'
Epoch 0:   0%|          | 0/4957 [00:49<?, ?it/s]`
![image](https://github.com/user-attachments/assets/0a5c6b8d-327e-4fe0-803d-f171b071e997)
and my running command then is: 
`CUDA_VISIBLE_DEVICES=0 python open3dsg/scripts/run.py --dump_features --dataset scannet --scales 3 --top_k_frames 5 --clip_model OpenSeg`
You mentioned that we can separately export the two feature without any more details, so I tried to separately activate the hyperparameter. I don't know if it is the proper way. Hope you can provide some details in your README.md. 
This is very important for our project, so I kindly hope you can reply at your earliest convenience. Thanks a lot for your help!

**Comment by Young-Loser** [comment]
Hello, I am a 2024 graduate of the Automation program at Shandong University. I saw your comment under the open3dsg project. I am also working on reproducing this project, primarily for use in robotic applications to conduct validation research on hardware. I believe our research goals won't conflict with yours. I would like to ask if we could have a discussion about the open3dsg project. I have encountered some issues while reproducing the project and would like to seek your advice if possible. I noticed that the WeChat contact information on your profile is no longer valid, and I hope to get in touch with you. My WeChat ID is: XC-992997. My email is: [1339241893@qq.com](mailto:1339241893@qq.com). Thank you!
您好，我是2024届山东大学自动化专业毕业生。我看到您在open3dsg项目下的留言。我也在复现这个项目，我们主要做机器人方向用来在硬件上进行验证研究。我想不会和您的研究想法冲突。我想问能否和您在open3dsg项目上做一下探讨交流？我在复现这个项目遇到一些疑问想要请教您，不知道是否可以？我在您主页上看到您的微信联系方式失效了，希望可以和您取得联系，谢谢！我的微信为：XC-992997。电子邮箱为：[1339241893@qq.com](mailto:1339241893@qq.com)。

**Comment by mfp0610** [comment]
I solved this problem by training the OpenSeg feature first and followed by the BLIP feature.
