### ISSUE TITLE
Missing file---The download link for the file 3DSSG_subset.zip is no longer valid.

### ISSUE THREAD

**Issue by Young-Loser** [boschresearch/Open3DSG#6]
Hello, I tried to download the 3DSSG_subset.zip file from your project homepage, but the download link [3DSSG_subset.zip](http://campar.in.tum.de/public_datasets/3DSSG/3DSSG_subset.zip) seems to be invalid. Could you please upload a new download link? Alternatively, could you let me know where I can download this file? Thank you!

**Comment by kochsebastian** [comment]
Unfortunately, I can't reproduce this issue. The download link that you referenced is valid for me
